name: Deploy Lambda

on:
  push:
    branches: [ "main" ]
    paths:
      - "src/agent/**"
      - "src/aws_lambda/**"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      #- name: Install Poetry
      #  run: pip install poetry

      #- name: Export dependencies
      #  run: poetry export -f requirements.txt --output requirements.txt --without-hashes

      - name: Package Lambda
        run: |
          mkdir -p build
          cp -r src/aws_lambda build/src/
          cp -r src/agent build/src/
          cd build && zip -r ../lambda_package.zip .

      - name: Deploy to AWS Lambda
        uses: appleboy/lambda-action@v0.2.0
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: "us-east-1"
          function_name: "datadoctor-chat"
          zip_file: "lambda_package.zip"